Imports

In [149]:
import requests
import pandas as pd
import time

help funktion for building the right URL

In [150]:
TMDB_API_KEY = "381056fa40bc22a39a9b6c16f58a2465"
BASE_URL = "https://api.themoviedb.org/3"
def tmdb_get(endpoint, params=None, timeout=10):
    if params is None:
        params = {}
    params["api_key"] = TMDB_API_KEY

    url = BASE_URL + endpoint
    r = requests.get(url, params = params, timeout = timeout)
    r.raise_for_status()
    r.status_code
    return r.json()

turning response in data

Collect movie id´s to sort

In [151]:
def collect_movie_ids(pages=10):
    all_movies = []

    for page in range(1, pages+1):
        data = tmdb_get(
            "/discover/movie",
            params={
                "sort_by": "popularity.desc",
                "page": page,
                "language": "en-US"
            }
        )
        all_movies.extend(data["results"])
        time.sleep(0.2)
    return pd.DataFrame(all_movies)

In [152]:
df = collect_movie_ids(pages=1)
df[["title","popularity"]].head(10)

                             title  popularity
0                          Shelter    456.5931
1                            Mercy    308.7706
2                        The Bluff    353.5452
3                      The Orphans    187.8834
4                         Hellfire    210.9411
5                  A Woman Scorned    164.4347
6        Your Heart Will Be Broken    188.3760
7            Return to Silent Hill    182.0890
8  28 Years Later: The Bone Temple    149.3133
9                The Shadow's Edge    161.8630

In [153]:
df = df.sort_values("popularity", ascending=False).reset_index(drop=True)

df[["title", "popularity","id"]].head(100)

                              title  popularity       id
0                           Shelter    456.5931  1290821
1                         The Bluff    353.5452   799882
2                             Mercy    308.7706  1236153
3                          Hellfire    210.9411  1088434
4         Your Heart Will Be Broken    188.3760  1523145
5                       The Orphans    187.8834  1244975
6             Return to Silent Hill    182.0890   680493
7                   A Woman Scorned    164.4347  1301306
8                          Scream 7    162.9968  1159559
9                 The Shadow's Edge    161.8630  1419406
10                       Zootopia 2    154.6525  1084242
11  28 Years Later: The Bone Temple    149.3133  1272837
12                        Hierarchy    146.2283  1461181
13           Greenland 2: Migration    137.4235   840464
14                    The Housemaid    117.0776  1368166
15             Avatar: Fire and Ash    112.3288    83533
16                The Wrecking Crew    104.6516  1168190
17                War of the Worlds    100.8897   755898
18               Predator: Badlands     99.3128  1242898
19                     Deathstalker     98.9774  1253000

In [154]:

df
df.columns

Index(['adult', 'backdrop_path', 'genre_ids', 'id', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'release_date', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='str')

In [155]:
def fetch_costs_revenue(movie_id, language= "en-US"):
    d = tmdb_get(f"/movie/{int(movie_id)}", params={"language": language})
    return{
        "id": d.get("id"),
        "budget":d.get("budget"),
        "revenue":d.get("revenue")
    }

In [156]:
for movie_id in df["id"]:
    print(fetch_costs_revenue(movie_id))

{'id': 1290821, 'budget': 50000000, 'revenue': 26786795}
{'id': 799882, 'budget': 0, 'revenue': 0}
{'id': 1236153, 'budget': 60000000, 'revenue': 49463290}
{'id': 1088434, 'budget': 0, 'revenue': 0}
{'id': 1523145, 'budget': 0, 'revenue': 0}
{'id': 1244975, 'budget': 0, 'revenue': 0}
{'id': 680493, 'budget': 23000000, 'revenue': 41586056}
{'id': 1301306, 'budget': 0, 'revenue': 0}
{'id': 1159559, 'budget': 45000000, 'revenue': 7500000}
{'id': 1419406, 'budget': 0, 'revenue': 174400000}
{'id': 1084242, 'budget': 150000000, 'revenue': 1849637495}
{'id': 1272837, 'budget': 63000000, 'revenue': 58586229}
{'id': 1461181, 'budget': 0, 'revenue': 0}
{'id': 840464, 'budget': 90000000, 'revenue': 39924680}
{'id': 1368166, 'budget': 35000000, 'revenue': 383000000}
{'id': 83533, 'budget': 350000000, 'revenue': 1474270032}
{'id': 1168190, 'budget': 78500000, 'revenue': 89000000}
{'id': 755898, 'budget': 10000000, 'revenue': 0}
{'id': 1242898, 'budget': 105000000, 'revenue': 184500000}
{'id': 1253000, 'budget': 100000, 'revenue': 0}

In [157]:
print(df2)

{'id': 1290821, 'budget': 50000000, 'revenue': 26786795}

In [165]:
df2 = pd.read_csv("/Users/tomfrandsen/Desktop/Datascienced_projekt/ds_project/data/the_oscar_award.csv")

In [166]:
df2.head()

,year_film,year_ceremony,ceremony,category,canon_category,name,film,winner
0,1927,1928,1,ACTOR,ACTOR IN A LEADING ROLE,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,ACTOR IN A LEADING ROLE,Richard Barthelmess,The Patent Leather Kid,False
2,1927,1928,1,ACTOR,ACTOR IN A LEADING ROLE,Emil Jannings,The Last Command,True
3,1927,1928,1,ACTOR,ACTOR IN A LEADING ROLE,Emil Jannings,The Way of All Flesh,True
4,1927,1928,1,ACTRESS,ACTRESS IN A LEADING ROLE,Louise Dresser,A Ship Comes In,False

In [184]:

df2[df2["name"].str.contains("jake", case=False, na=False)]

,year_film,year_ceremony,ceremony,category,canon_category,name,film,winner
7669,1996,1997,69,MAKEUP,MAKEUP AND HAIRSTYLING,Michael Westmore/Scott Wheeler/Jake Garber,Star Trek: First Contact,False
8651,2005,2006,78,ACTOR IN A SUPPORTING ROLE,ACTOR IN A SUPPORTING ROLE,Jake Gyllenhaal,Brokeback Mountain,False
10036,2016,2017,89,FILM EDITING,FILM EDITING,Jake Roberts,Hell or High Water,False